Listener to consume `issue_comments` webhook, parse and send ETH to address.
aragon/autobounty pull request #2
Opened 2017-06-11 10:45 UTC by snugghash

Fixes #1.

### Implementation
Commiteth bot comments with address and bounty, address is parsed and stored in a dict (key is issueId, from the POST webhook). This is not persistent across server restart.
When a comment says `@autobounty x ETH` tries to award `x` ETH to the previously stored address. 

### Code review focus
Must check security / robustness of the string parsing, for both address and amount.
Authentication for who is allowed to award ETH.

### Testing
Curl:
```
echo '{"comment":{"body":"Contract address: 0x19d8acac27553ef390d287b532b"}, "issue":{"id":234234}}' | curl -H "Content-Type: application/json" -X POST -d @- localhost:8181/address/1

echo '{"text": "Hello **world**!", "comment":{"body":"@autobounty 1 ETH"}, "issue":{"id":234234}}' | curl -H "Content-Type: application/json" -X POST -d @- localhost:8181/address/1
```
Didn't write automated tests or test manually with an actual Github webhook.

2017-06-13 14:38 UTC, izqui requested changes

2017-06-13 14:38 UTC, izqui commented on index.js
> +app.post('/address/:address', jsonParser, function(req, res, next){
Why is the ':address' kept here? Doesn't look it is used anywhere with `req.params.address`

2017-06-13 14:38 UTC, izqui commented on index.js
> +    issueData[issueId] = {"toAddress": commentBody.substring(commentBody.search("Contract address:") + 18, commentBody.search("Contract address:") + 60)}
We should assert that it is the commiteth username who made the comment with the address

2017-06-13 14:38 UTC, izqui commented on index.js
> +        from: address, // Specified in webhook, secret
But this address variable comes from the env variable, right? No reason for it to be secret

2017-06-13 14:38 UTC, izqui commented on index.js
> +        data: '0xde5f72fd', // sha3('faucet()')
We can get rid of this

2017-06-14 04:02 UTC, snugghash commented on index.js
> +        from: address, // Specified in webhook, secret
How about security? If I understand this correctly, anybody can send some JSON emulating GitHub's (even with the verification that commiteth has commented the address). The exact implementation is up to you, but I think the listening address should be secret (or have some verification that it is GitHub). Holding off on this until your response.

2017-06-14 04:02 UTC, snugghash commented on index.js
> +    issueData[issueId] = {"toAddress": commentBody.substring(commentBody.search("Contract address:") + 18, commentBody.search("Contract address:") + 60)}
Will finish in <6 hours.

2017-06-14 04:04 UTC, snugghash commented on index.js
> +app.post('/address/:address', jsonParser, function(req, res, next){
Agreed, vestigial, removing now. 

Problem is, I didn't figure out how secure stuff would be. Related would be the secrecy of the receiving address (known only to GitHub, for example)

2017-06-14 04:05 UTC, snugghash commented on index.js
> +        data: '0xde5f72fd', // sha3('faucet()')
Aren't these four lines critical to the transaction? Do you mean `data` field alone?

2017-06-14 07:28 UTC, izqui commented on index.js
> +        from: address, // Specified in webhook, secret
Hmm, I hadn't thought about this. I agree that we need to give Github a URL that contains a secret, and only accept requests with the correct secret (but we should call it secret, no need to relate it with the address) :)

2017-06-14 07:28 UTC, izqui commented on index.js
> +        data: '0xde5f72fd', // sha3('faucet()')
Meant only the data part, it is a specific data to make it display faucet transactions in Aragon Core

2017-06-14 11:52 UTC, snugghash commented
Pushed changes reflecting everything except the security bit.

2017-06-14 11:55 UTC, snugghash commented on index.js
> +        data: '0xde5f72fd', // sha3('faucet()')
Done.

2017-06-14 11:55 UTC, snugghash commented on index.js
> +    issueData[issueId] = {"toAddress": commentBody.substring(commentBody.search("Contract address:") + 18, commentBody.search("Contract address:") + 60)}
Done.

2017-06-14 11:55 UTC, snugghash commented on index.js
> +app.post('/address/:address', jsonParser, function(req, res, next){
Done.

2017-06-14 12:30 UTC, izqui approved these changes
Cool, LGTM now

2017-06-14 12:30 UTC, merged

2017-06-14 13:46 UTC, snugghash commented on index.js
> +        from: address, // Specified in webhook, secret
So, to summarize, the current situation is that the address the webhook uses should be secret and is an env. variable, and its compromise can lead to full financial loss.

2017-06-14 13:48 UTC, snugghash commented on index.js
> +        from: address, // Specified in webhook, secret
Oh waitamin, what's the fromAddress of the eth. transaction supposed to be? Is it the same as the env variable? Then everybody who can access the blockchain (or the receiver of transactions), would know this and can jeopardize everything.